/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Pablo Valentini
 */
public class Menu extends javax.swing.JFrame {

 
    public Menu() {
        initComponents();
        this.setTitle("Sistema educativo - Valentini");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitulo_tabla = new javax.swing.JLabel();
        jPMain = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jBLis_Alumnos = new javax.swing.JButton();
        jBList_Profesores = new javax.swing.JButton();
        jBList_Materias = new javax.swing.JButton();
        jBList_Cursado = new javax.swing.JButton();
        jBList_Inscripciones = new javax.swing.JButton();
        jBList_Carreras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLTitulo_tabla.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLTitulo_tabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo_tabla.setText("Título tabla");
        jLTitulo_tabla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPMain.setLayout(new java.awt.CardLayout());

        jBLis_Alumnos.setBackground(new java.awt.Color(255, 255, 255));
        jBLis_Alumnos.setForeground(new java.awt.Color(51, 51, 51));
        jBLis_Alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/010-graduate avatar.png"))); // NOI18N
        jBLis_Alumnos.setText("Alumnos");
        jBLis_Alumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBLis_Alumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBList_Profesores.setBackground(new java.awt.Color(255, 255, 255));
        jBList_Profesores.setForeground(new java.awt.Color(0, 0, 0));
        jBList_Profesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/015-owl.png"))); // NOI18N
        jBList_Profesores.setText("Profesores");
        jBList_Profesores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBList_Profesores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBList_Materias.setBackground(new java.awt.Color(255, 255, 255));
        jBList_Materias.setForeground(new java.awt.Color(0, 0, 0));
        jBList_Materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/016-pen.png"))); // NOI18N
        jBList_Materias.setText("Materias");
        jBList_Materias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBList_Materias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBList_Cursado.setBackground(new java.awt.Color(255, 255, 255));
        jBList_Cursado.setForeground(new java.awt.Color(0, 0, 0));
        jBList_Cursado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/014-online education.png"))); // NOI18N
        jBList_Cursado.setText("Cursado");
        jBList_Cursado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBList_Cursado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBList_Inscripciones.setBackground(new java.awt.Color(255, 255, 255));
        jBList_Inscripciones.setForeground(new java.awt.Color(0, 0, 0));
        jBList_Inscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/018-campus.png"))); // NOI18N
        jBList_Inscripciones.setText("Inscripción");
        jBList_Inscripciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBList_Inscripciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBList_Carreras.setBackground(new java.awt.Color(255, 255, 255));
        jBList_Carreras.setForeground(new java.awt.Color(0, 0, 0));
        jBList_Carreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/003-book.png"))); // NOI18N
        jBList_Carreras.setText("Carreras");
        jBList_Carreras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBList_Carreras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jBList_Carreras)
                .addGap(18, 18, 18)
                .addComponent(jBList_Inscripciones)
                .addGap(18, 18, 18)
                .addComponent(jBLis_Alumnos)
                .addGap(18, 18, 18)
                .addComponent(jBList_Cursado)
                .addGap(18, 18, 18)
                .addComponent(jBList_Materias)
                .addGap(18, 18, 18)
                .addComponent(jBList_Profesores)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBLis_Alumnos)
                    .addComponent(jBList_Profesores)
                    .addComponent(jBList_Materias)
                    .addComponent(jBList_Cursado)
                    .addComponent(jBList_Inscripciones)
                    .addComponent(jBList_Carreras))
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Educación");

        jBayuda.setBackground(new java.awt.Color(76, 155, 163));
        jBayuda.setText("Ayuda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addComponent(jPMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLTitulo_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitulo_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPMain, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBLis_Alumnos;
    private javax.swing.JButton jBList_Carreras;
    private javax.swing.JButton jBList_Cursado;
    private javax.swing.JButton jBList_Inscripciones;
    private javax.swing.JButton jBList_Materias;
    private javax.swing.JButton jBList_Profesores;
    private javax.swing.JButton jBayuda;
    private javax.swing.JLabel jLTitulo_tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getjBLis_Alumnos() {
        return jBLis_Alumnos;
    }

    public void setjBLis_Alumnos(javax.swing.JButton jBLis_Alumnos) {
        this.jBLis_Alumnos = jBLis_Alumnos;
    }

    public javax.swing.JButton getjBList_Carreras() {
        return jBList_Carreras;
    }

    public void setjBList_Carreras(javax.swing.JButton jBList_Carreras) {
        this.jBList_Carreras = jBList_Carreras;
    }

    public javax.swing.JButton getjBList_Cursado() {
        return jBList_Cursado;
    }

    public void setjBList_Cursado(javax.swing.JButton jBList_Cursado) {
        this.jBList_Cursado = jBList_Cursado;
    }

    public javax.swing.JButton getjBList_Inscripciones() {
        return jBList_Inscripciones;
    }

    public void setjBList_Inscripciones(javax.swing.JButton jBList_Inscripciones) {
        this.jBList_Inscripciones = jBList_Inscripciones;
    }

    public javax.swing.JButton getjBList_Materias() {
        return jBList_Materias;
    }

    public void setjBList_Materias(javax.swing.JButton jBList_Materias) {
        this.jBList_Materias = jBList_Materias;
    }

    public javax.swing.JButton getjBList_Profesores() {
        return jBList_Profesores;
    }

    public void setjBList_Profesores(javax.swing.JButton jBList_Profesores) {
        this.jBList_Profesores = jBList_Profesores;
    }

    public javax.swing.JLabel getjLTitulo_tabla() {
        return jLTitulo_tabla;
    }

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public javax.swing.JPanel getjPMain() {
        return jPMain;
    }

    public void setjPMain(javax.swing.JPanel jPMain) {
        this.jPMain = jPMain;
    }

    public javax.swing.JButton getjBayuda() {
        return jBayuda;
    }

    public void setjBayuda(javax.swing.JButton jBayuda) {
        this.jBayuda = jBayuda;
    }


}
