/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Pablo Valentini
 */
public class Vista_Alumno extends javax.swing.JFrame {

    public Vista_Alumno() {
        initComponents();
        this.setTitle("SE - Alumnos");
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlumno = new javax.swing.JPanel();
        jLnombre = new javax.swing.JLabel();
        jLdni = new javax.swing.JLabel();
        jLtelefono = new javax.swing.JLabel();
        jLapellido = new javax.swing.JLabel();
        jLdomicilio = new javax.swing.JLabel();
        jLfecNac = new javax.swing.JLabel();
        jLcodInsc = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTDNI = new javax.swing.JTextField();
        jTDomicilio = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTTelefono = new javax.swing.JTextField();
        jCcodInsc = new javax.swing.JComboBox<>();
        jBagregar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jDfecNac = new datechooser.beans.DateChooserCombo();
        jBeditar = new javax.swing.JButton();
        jLtituloAlumno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLnombre.setText("Nombre");

        jLdni.setText("DNI");

        jLtelefono.setText("Teléfono");

        jLapellido.setText("Apellido");

        jLdomicilio.setText("Domicilio");

        jLfecNac.setText("Fecha Nac.");

        jLcodInsc.setText("Cod. Insc.");

        jBagregar.setBackground(new java.awt.Color(85, 147, 98));
        jBagregar.setText("Guardar");

        jBcancelar.setBackground(new java.awt.Color(211, 33, 46));
        jBcancelar.setText("Cancelar");

        jDfecNac.setLocale(new java.util.Locale("", "", ""));

        jBeditar.setBackground(new java.awt.Color(255, 204, 51));
        jBeditar.setText("Editar");

        jLtituloAlumno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLtituloAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloAlumno.setText("Título");
        jLtituloAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
        jPanelAlumno.setLayout(jPanelAlumnoLayout);
        jPanelAlumnoLayout.setHorizontalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                    .addGap(27, 27, 27)
                                    .addComponent(jLnombre))
                                .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                    .addContainerGap(27, Short.MAX_VALUE)
                                    .addComponent(jLcodInsc)))
                            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLdni)
                                    .addComponent(jLtelefono))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCcodInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLapellido)
                            .addComponent(jLdomicilio)
                            .addComponent(jLfecNac))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jDfecNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addGap(0, 331, Short.MAX_VALUE)
                        .addComponent(jBagregar)
                        .addGap(18, 18, 18)
                        .addComponent(jBeditar)
                        .addGap(18, 18, 18)
                        .addComponent(jBcancelar)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLtituloAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAlumnoLayout.setVerticalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtituloAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCcodInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcodInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLfecNac)
                    .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLnombre)
                            .addComponent(jTApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLapellido))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLdni)
                            .addComponent(jLdomicilio)
                            .addComponent(jTDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLtelefono))
                            .addComponent(jDfecNac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBagregar)
                    .addComponent(jBcancelar)
                    .addComponent(jBeditar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBeditar;
    private javax.swing.JComboBox<Integer> jCcodInsc;
    private datechooser.beans.DateChooserCombo jDfecNac;
    private javax.swing.JLabel jLapellido;
    private javax.swing.JLabel jLcodInsc;
    private javax.swing.JLabel jLdni;
    private javax.swing.JLabel jLdomicilio;
    private javax.swing.JLabel jLfecNac;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLtelefono;
    private javax.swing.JLabel jLtituloAlumno;
    private javax.swing.JPanel jPanelAlumno;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTDNI;
    private javax.swing.JTextField jTDomicilio;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTTelefono;
    // End of variables declaration//GEN-END:variables



    public javax.swing.JButton getjBagregar() {
        return jBagregar;
    }

    public void setjBagregar(javax.swing.JButton jBagregar) {
        this.jBagregar = jBagregar;
    }

    public javax.swing.JButton getjBcancelar() {
        return jBcancelar;
    }

    public void setjBcancelar(javax.swing.JButton jBcancelar) {
        this.jBcancelar = jBcancelar;
    }

    public javax.swing.JComboBox<Integer> getjCcodInsc() {
        return jCcodInsc;
    }

    public void setjCcodInsc(javax.swing.JComboBox<Integer> jCcodInsc) {
        this.jCcodInsc = jCcodInsc;
    }

    public javax.swing.JTextField getjTApellido() {
        return jTApellido;
    }

    public void setjTApellido(javax.swing.JTextField jTApellido) {
        this.jTApellido = jTApellido;
    }

    public javax.swing.JTextField getjTDNI() {
        return jTDNI;
    }

    public void setjTDNI(javax.swing.JTextField jTDNI) {
        this.jTDNI = jTDNI;
    }

    public javax.swing.JTextField getjTDomicilio() {
        return jTDomicilio;
    }

    public void setjTDomicilio(javax.swing.JTextField jTDomicilio) {
        this.jTDomicilio = jTDomicilio;
    }

    public javax.swing.JTextField getjTNombre() {
        return jTNombre;
    }

    public void setjTNombre(javax.swing.JTextField jTNombre) {
        this.jTNombre = jTNombre;
    }

    public javax.swing.JTextField getjTTelefono() {
        return jTTelefono;
    }

    public void setjTTelefono(javax.swing.JTextField jTTelefono) {
        this.jTTelefono = jTTelefono;
    }

    public datechooser.beans.DateChooserCombo getjDfecNac() {
        return jDfecNac;
    }

    public void setjDfecNac(datechooser.beans.DateChooserCombo jDfecNac) {
        this.jDfecNac = jDfecNac;
    }

    public javax.swing.JButton getjBeditar() {
        return jBeditar;
    }

    public void setjBeditar(javax.swing.JButton jBeditar) {
        this.jBeditar = jBeditar;
    }

    public javax.swing.JLabel getjLtituloAlumno() {
        return jLtituloAlumno;
    }

    public void setjLtituloAlumno(javax.swing.JLabel jLtituloAlumno) {
        this.jLtituloAlumno = jLtituloAlumno;
    }

    
 
}
